apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-config
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  FEATURE_FLAG: {{ .Values.env.FEATURE_FLAG | quote }}
  HOST_URL: {{ .Values.env.HOST_URL | quote }}
  HOST_PORT: {{ .Values.env.HOST_PORT | quote }}