name: matrix

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  DEV:
    name: Build & Test For DEV
    runs-on: ${{ matrix.os }}
    environment: DEV
    
    strategy:
      matrix:
        python: [3.12]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello, CI with GitHub Actions!"

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint *.py || true
    
  QA:
    name: Build & Test For QA
    runs-on: ${{ matrix.os }}
    environment: QA
    needs: DEV
    
    strategy:
      matrix:
        python: [3.11, 3.12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello, CI with GitHub Actions!"

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint *.py || true

  PROD:
    name: Build & Test For PROD
    runs-on: ${{ matrix.os }}
    environment: PROD
    needs: QA
    
    strategy:
      matrix:
        python: [3.12]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello, CI with GitHub Actions!"

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint *.py || true

  helm-publish-docker:
    name: Publish Helm Chart to Docker Hub
    runs-on: ubuntu-latest
    needs: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set chart version
        run: |
          PACKAGE_VERSION=$(grep '^version:' ./mychart/Chart.yaml | awk '{print $2}')
          PACKAGE_NAME=$(grep '^name:' ./mychart/Chart.yaml | awk '{print $2}')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "Detected name: $PACKAGE_NAME"
          echo "Detected version: $PACKAGE_VERSION"
          
      - name: Package Helm chart as OCI image
        run: |
           helm package ./mychart
           
      - name: Log in to Docker Hub for Helm
        run: |
               helm registry login registry-1.docker.io \
                -u ${{ secrets.DOCKER_HUB_USERNAME }} \
                -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Push Helm chart to Docker Hub
        run: |
          helm push ${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz oci://registry-1.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}

  
  
  
  
  








          
